global:
  resolve_timeout: 5m
  http_config:
    follow_redirects: true
    enable_http2: true
  smtp_hello: localhost
  smtp_require_tls: true
  telegram_api_url: https://api.telegram.org
route:
  receiver: 'telepush'
  group_by: ['alertname', 'instance', 'severity']
  continue: false
  group_wait: 30s
  group_interval: 10s
  repeat_interval: 1h
inhibit_rules:
- source_match:
    severity: 'critical'
  target_match:
    severity: 'warning'
  equal: ['alertname', 'dev', 'instance']
receivers:
- name: 'telepush'
  webhook_configs:
  - send_resolved: true
    http_config:
      follow_redirects: true
      enable_http2: true
    url: https://telepush.dev/api/inlets/alertmanager/8cd8fe
    max_alerts: 0
templates: []
